<?xml version="1.0" encoding="utf-8"?><Database Name="paking" Class="DataloginDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP;Initial Catalog=paking;Integrated Security=True;Connect Timeout=30;Encrypt=False;Trust Server Certificate=False" SettingsObjectName="CarParking.Properties.Settings" SettingsPropertyName="pakingConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.login" Member="logins">
    <Type Name="login">
      <Column Name="Id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[user]" Member="user" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="pass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="role" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>