#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarParking
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="paking")]
	public partial class Parking_Car_DetailDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertParkingSpace(ParkingSpace instance);
    partial void UpdateParkingSpace(ParkingSpace instance);
    partial void DeleteParkingSpace(ParkingSpace instance);
    #endregion
		
		public Parking_Car_DetailDataContext() : 
				base(global::CarParking.Properties.Settings.Default.pakingConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Parking_Car_DetailDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Parking_Car_DetailDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Parking_Car_DetailDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Parking_Car_DetailDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ParkingSpace> ParkingSpaces
		{
			get
			{
				return this.GetTable<ParkingSpace>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ParkingSpace")]
	public partial class ParkingSpace : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<bool> _Status;
		
		private System.Nullable<int> _Price;
		
		private string _ID_Car_using;
		
		private System.Nullable<System.DateTime> _Date_Come;
		
		private System.Nullable<System.DateTime> _Date_Leave;
		
		private System.Nullable<double> _Revenue;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    partial void OnPriceChanging(System.Nullable<int> value);
    partial void OnPriceChanged();
    partial void OnID_Car_usingChanging(string value);
    partial void OnID_Car_usingChanged();
    partial void OnDate_ComeChanging(System.Nullable<System.DateTime> value);
    partial void OnDate_ComeChanged();
    partial void OnDate_LeaveChanging(System.Nullable<System.DateTime> value);
    partial void OnDate_LeaveChanged();
    partial void OnRevenueChanging(System.Nullable<double> value);
    partial void OnRevenueChanged();
    #endregion
		
		public ParkingSpace()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
		public System.Nullable<bool> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Int")]
		public System.Nullable<int> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Car_using", DbType="NChar(10)")]
		public string ID_Car_using
		{
			get
			{
				return this._ID_Car_using;
			}
			set
			{
				if ((this._ID_Car_using != value))
				{
					this.OnID_Car_usingChanging(value);
					this.SendPropertyChanging();
					this._ID_Car_using = value;
					this.SendPropertyChanged("ID_Car_using");
					this.OnID_Car_usingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_Come", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date_Come
		{
			get
			{
				return this._Date_Come;
			}
			set
			{
				if ((this._Date_Come != value))
				{
					this.OnDate_ComeChanging(value);
					this.SendPropertyChanging();
					this._Date_Come = value;
					this.SendPropertyChanged("Date_Come");
					this.OnDate_ComeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_Leave", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date_Leave
		{
			get
			{
				return this._Date_Leave;
			}
			set
			{
				if ((this._Date_Leave != value))
				{
					this.OnDate_LeaveChanging(value);
					this.SendPropertyChanging();
					this._Date_Leave = value;
					this.SendPropertyChanged("Date_Leave");
					this.OnDate_LeaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Revenue", DbType="Float")]
		public System.Nullable<double> Revenue
		{
			get
			{
				return this._Revenue;
			}
			set
			{
				if ((this._Revenue != value))
				{
					this.OnRevenueChanging(value);
					this.SendPropertyChanging();
					this._Revenue = value;
					this.SendPropertyChanged("Revenue");
					this.OnRevenueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
